### ISSUE TITLE
tests fail on node >= v12.16.0

### ISSUE THREAD

**Issue by davidfirst** [dependents/node-module-lookup-amd#28]
I get the error below when running `npm test`. I verified with multiple node versions and it happens only on versions >= v12.16.0.
This issue happens also on projects that depend on this module, such as `filling-cabinet`.

```
➜  node-module-lookup-amd git:(master) ✗ npm test

> module-lookup-amd@6.2.0 test /Users/davidfirst/temp/projects/node-module-lookup-amd
> jscs index.js test bin && mocha test/test.js

/Users/davidfirst/temp/projects/node-module-lookup-amd/node_modules/requirejs/bin/r.js:1
(function (exports, require, module, __filename, __dirname) { #!/usr/bin/env node
                                                              ^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:88:7)
    at createScript (vm.js:263:10)
    at Object.runInThisContext (vm.js:311:10)
    at wrapSafe (internal/modules/cjs/loader.js:1058:15)
    at Module._compile (internal/modules/cjs/loader.js:1121:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Module.require (internal/modules/cjs/loader.js:1043:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at /Users/davidfirst/temp/projects/node-module-lookup-amd/index.js:9:19
    at Object.<anonymous> (/Users/davidfirst/temp/projects/node-module-lookup-amd/index.js:258:4)
```

**Comment by davidfirst** [comment]
After some debugging, the issue is coming from the `rewire` package.
They have an open issue about it: https://github.com/jhnns/rewire/issues/178.

In this repo, I don't see why `rewire` is needed for the tests, it can be removed altogether.

**Comment by mrjoelkemp** [comment]
Thanks @davidfirst! I appreciate the help figuring out the issue. I subscribed to the issue and will push a fix when they release the patch.
